[versions]
atlantafx = "2.1.0"
bouncycastle = "1.83"
commons-logging = "1.3.4"
h2database = "2.4.240"
ikonli = "12.4.0"
javafx = "23.0.2"
jimfs = "1.3.1"
jmh = "1.37"
jspecify = "1.0.0"
junit-bom = "6.0.2"
log4j-bom = "2.25.3"
miglayout = "11.4.2"
slb4j = "0.1-beta"
slf4j = "2.0.17"
spotbugs = "4.9.8"

# Plugins
cabe-plugin = "3.3.0"
jdk-plugin = "0.4.0"
jmh-plugin = "0.7.3"
jreleaser-plugin = "1.22.0"
native-plugin = "0.11.3"
sonar-plugin = "7.2.2.6593"
spotbugs-plugin = "6.4.8"
test-logger-plugin = "4.0.0"
versions-plugin = "0.53.0"

[libraries]
atlantafx = { group = "io.github.mkpaz", name = "atlantafx-base", version.ref = "atlantafx" }
bouncycastle-pkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-provider = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
commons-logging = { group = "commons-logging", name = "commons-logging", version.ref = "commons-logging" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2database" }
ikonli-fontawesome6 = { group = "org.kordamp.ikonli", name = "ikonli-fontawesome6-pack", version.ref = "ikonli" }
ikonli-javafx = { group = "org.kordamp.ikonli", name = "ikonli-javafx", version.ref = "ikonli" }
jimfs = { group = "com.google.jimfs", name = "jimfs", version.ref = "jimfs" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j-bom" }
miglayout-swing = { group = "com.miglayout", name = "miglayout-swing", version.ref = "miglayout" }
sawmill-carpenter = { group = "com.dua3.sawmill", name = "carpenter", version.ref = "slb4j" }
sawmill-carpenter-swing = { group = "com.dua3.sawmill", name = "carpenter-swing", version.ref = "slb4j" }
slb4j = { group = "org.slb4j", name = "slb4j", version.ref = "slb4j" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

[plugins]
cabe = { id = "com.dua3.cabe", version.ref = "cabe-plugin" }
jdk = { id = "com.dua3.gradle.jdkprovider", version.ref = "jdk-plugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser-plugin" }
native = { id = "org.graalvm.buildtools.native", version.ref = "native-plugin" }
sonar = { id = "org.sonarqube", version.ref = "sonar-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
